web:
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - db
 
php:
    image: projetusti/php
    restart: always
    links:
        - db
    volumes:
        - ./code:/code
        
db:
    image: mysql:latest
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    volumes:
        - ./data:/var/lib/mysql
        
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - "8080:80"
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
    links:
        - db